build-container:
  image:
    name: "nixos/nix"
  script:
    - mkdir -p "$HOME/.config/nix"
    - echo 'experimental-features = nix-command flakes' > "$HOME/.config/nix/nix.conf"
    - nix -L build .#docker
